samples:
    - ILZW_RNAseq_G086_GATCAG_Arachis_hypogaea_I801_L5
    - IMAT_RNAseq_T052_CTTGTA_Arachis_hypogaea_I801_L6 
    - ILXM_RNAseq_T090_TAGCTT_Arachis_hypogaea_I801_L2
    - IMAR_RNAseq_T102_TAGCTT_Arachis_hypogaea_I801_L6